### ISSUE TITLE
Data types supported

### ISSUE THREAD

**Issue by dnlopes** [dclements/riak-java-crdt#1]
Hi,
do you intend to extend the CRDTs supported? Like LWW-Set or PN-Set?

If you don't, do you know where can I find such implementations?

**Comment by dclements** [comment]
@dnlopes This is mostly just a toy project so that I could play around with implementations, so I might if I get back to it but I don't have specific plans to do so at this time. 

As to implementations it depends on what exactly you are looking for. If you are looking for the ability to use such in Riak, Riak 2.0 will contain excellent [data type support](http://basho.com/introducing-riak-2-0/). If you are looking at such for learning or educational purposes I don't know of one written in Java, but I have seen implementations in other languages (e.g., [python](https://github.com/ericmoritz/crdt) and [haskell](https://github.com/mgsloan/crdt/blob/master/src/Data/CRDT/Set.hs)). I also don't think they'd be difficult to implement in Java if you wanted to do so and submit a PR.

**Comment by dnlopes** [comment]
Thanks for the fast reply. The v2.0 of Riak looks promising. Thanks for pointing that out. 

I will close this issue now.
